### ISSUE TITLE
[Backlog] 고객센터 - customerList 컴포넌트

### ISSUE THREAD

**Issue by cheolgyun7** [Muhan-Company/bizcurator-ecommerce#13]
## Description

고객센터 페이지에 있는 List 보여주고 Dropdown기능 구비
### 고객센터 List 화면 UI 완성

 고객센터 List 화면 UI 퍼블리싱 완료

## Todo List
- [ ] 공지사항 리스트 컴포넌트 생성
- [ ] 자주하는 질문 리스트 컴포넌트 생성
- [ ] 공지사항 및 자주하는 질문 dropdown구현
