### ISSUE TITLE
[Backlog] 장바구니 페이지 - CartAPI

### ISSUE THREAD

**Issue by Hwa-J** [Muhan-Company/bizcurator-ecommerce#26]
### 장바구니 페이지 각종 기능 구현과 API를 연결합니다.

장바구니 페이지 기능 구현 및 API 연결

## Todo List
- [ ] 장바구니 페이지 전체선택 기능 구현
- [ ] 장바구니 페이지 선택삭제 기능 구현
- [ ] 장바구니 페이지 선택에 따라 결제정보 금액 계산 기능 구현

- [ ] 삭제버튼 클릭시 삭제 확인 모달 창 열리는 기능 구현
- [ ] 바로구매 페이지에서 장바구니 클릭시 상품 담기 모달 창 열리는 기능 구현
- [ ] 장바구니 상품 삭제 성공 모달창 열리고 3초 후에 닫히는 기능 구현
- [ ] 장바구니 상품 담기 성공 모달창 열리고 3초 후에 닫히는 기능 구현
