### ISSUE TITLE
[Backlog] 메인 페이지 - 상품 컴포넌트

### ISSUE THREAD

**Issue by Valentin1495** [Muhan-Company/bizcurator-ecommerce#34]
### 상품 컴포넌트 UI 완성
기능 제외

## Todo List
- [x] 이번 주 인기 급상승Top3 추천
- [x] 이번 달 인기제품 Toop3 추천
- [x] 비큐의 추천 제품 추천
- [x] 상품의 장바구니 아이콘 클릭 시 해당 상품의 장바구니 모달 등장
- [x] 장바구니 모달의 장바구니 담기 클릭 시 장바구니 확인 모달 등장
- [x] 수량에 따른 가격 변경 기능
