### ISSUE TITLE
[Backlog] 메인 페이지 - Footer & NavBar

### ISSUE THREAD

**Issue by Valentin1495** [Muhan-Company/bizcurator-ecommerce#35]
### 메인 페이지 Footer & NavBar UI 완성
기능 제외
## Todo List
- [x] Footer 컴포넌트 완성
- [x] NavBar 컴포넌트 완성
- [x] 로그인 클릭 시 모달 팝 업
- [x] 회원가입 클릭 시 회원가입 페이지로 이동
- [x] 고객센터 클릭 시 고객센터 페이지로 이동
