### ISSUE TITLE
[Backlog] 바로구매 페이지

### ISSUE THREAD

**Issue by Valentin1495** [Muhan-Company/bizcurator-ecommerce#41]
### 바로구매 페이지 화면 UI 완성

바로구매 페이지 기능 제외한 화면 UI 퍼블리싱 완료

## Todo List
- [x] 상단에 바로구매 눌렀을 때 바로구매 페이지로 이동
- [x] 필터기능(신상품, 인기순, 낮은 가격, 높은 가격)
- [x] 해당 카테고리 터치할 경우(스크롤한 뒤 클릭) 해당 카테고리에 맞는 제품 리스트 페이지로 이동 
- [x] 제품을 터치했을 경우 제품 상세 페이지로 이동 
- [x] 검색 기능
