### ISSUE TITLE
[Backlog] 마이페이지 - CancelRefundDetail

### ISSUE THREAD

**Issue by Hwa-J** [Muhan-Company/bizcurator-ecommerce#67]
### 취소, 환불 신청 상세 페이지 UI 완성

취소, 환불 신청 상세 페이지 UI 퍼블리싱 및 api 연결 완료

## Todo List
- [x] 취소 신청 상세 페이지 UI 완성
- [x] 환불 신청 상세 페이지 UI 완성
- [x] 취소 신청 상세 데이터 조회 API 연결
- [x] 환불 신청 상세 데이터 조회 API 연결
